version: '3.8'

services:
  # Redis 服务
  redis:
    image: redis:7-alpine
    container_name: autodatahub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - autodatahub-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL 服务
  mysql:
    image: mysql:8.0
    container_name: autodatahub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-autodatahub123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-autodatahub}
      MYSQL_USER: ${MYSQL_USER:-autodatahub}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-autodatahub123}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./pkg/models/tables.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - autodatahub-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 处理服务
  autodatahub-process:
    build: .
    container_name: autodatahub-process
    command: ["./process"]
    ports:
      - "8080:8080"  # 健康检查和监控指标端口
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
    networks:
      - autodatahub-network
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - REDIS_ADDR=redis:6379
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER:-autodatahub}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-autodatahub123}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-autodatahub}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 定时任务服务
  autodatahub-task:
    build: .
    container_name: autodatahub-task
    command: ["./task"]
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
    networks:
      - autodatahub-network
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - REDIS_ADDR=redis:6379
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER:-autodatahub}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-autodatahub123}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-autodatahub}
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  mysql_data:
    driver: local

networks:
  autodatahub-network:
    driver: bridge
