version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: autodatahub
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      start_period: 30s
    tmpfs:
      - /var/lib/mysql

  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
      start_period: 10s

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      mysql-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql-test
      MYSQL_PORT: 3306
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_DATABASE: autodatahub
      REDIS_ADDR: redis-test:6379
    volumes:
      - .:/app
    working_dir: /app
    command: go test -v ./tests/integration/...
