# AutoDataHub-monitor 配置文件

# Redis配置
redis:
  addr: "localhost:6379"      # Redis服务器地址
  password: ""               # Redis密码
  db: 0                      # Redis数据库编号
  queue_name: "negative_triggers"  # Redis队列名称

# 触发器配置
trigger:
  api_base_url: "http://localhost:8080" # API基础URL
  from_path: "/api/triggers"            # 元数据路径
  from_path_method: "POST"              # 调用方法
  trigger_id_list: [1,2,3,4,5,123,345,62,44,123]
  download_path: "/api/download"        # 下载pack文件路径
  download_path_method: "POST"          # 调用方法

# 日志配置
logger:
  level: "info"              # 日志级别：debug, info, warn, error, fatal
  file_path: "logs/app.log"  # 日志文件路径
  max_size: 100              # 单个日志文件最大大小（MB）
  max_backups: 3             # 最大保留的旧日志文件数量
  max_age: 7                 # 日志文件保留的最大天数
  compress: true             # 是否压缩旧日志文件
  console: true              # 是否同时输出到控制台

# MySQL配置
mysql:
  host: "localhost"          # MySQL主机地址
  port: 3306                 # MySQL端口
  username: "root"           # MySQL用户名
  password: ""               # MySQL密码
  database: "autodatahub"    # MySQL数据库名
  charset: "utf8mb4"         # 字符集

# 车辆类型配置
vehicle_type:
  default_queue: "default_triggers"
  # Usage type queues
  production_car_queue: "production_car_triggers"
  test_drive_car_queue: "test_drive_car_triggers"
  media_car_queue: "media_car_triggers"
  internal_car_queue: "internal_car_triggers"

  fusion_car_queue: "fusion_car_triggers"
  write_db_queue: "write_db_triggers"