# AutoDataHub-monitor 配置文件

# Redis配置
redis:
  addr: "localhost:6379"      # Redis服务器地址
  password: ""               # Redis密码
  db: 0                      # Redis数据库编号
  queue_name: "negative_triggers"  # Redis队列名称

# 触发器配置
trigger:
  api_base_url: "http://localhost:8080"  # API基础URL
  api_endpoint: "/api/triggers"          # API端点
  redis_addr: "localhost:6379"           # Redis服务器地址
  redis_password: ""                     # Redis密码
  redis_db: 0                            # Redis数据库编号
  redis_queue: "negative_triggers"       # Redis队列名称
  init_queue_name: "init_triggers"         # 初始化队列名称
  api_timeout: 30                        # 超时时间（秒）

# 日志配置
logger:
  level: "info"              # 日志级别：debug, info, warn, error, fatal
  file_path: "logs/app.log"  # 日志文件路径
  max_size: 100              # 单个日志文件最大大小（MB）
  max_backups: 3             # 最大保留的旧日志文件数量
  max_age: 7                 # 日志文件保留的最大天数
  compress: true             # 是否压缩旧日志文件
  console: true              # 是否同时输出到控制台

# MySQL配置
mysql:
  host: "localhost"          # MySQL主机地址
  port: 3306                 # MySQL端口
  username: "root"           # MySQL用户名
  password: ""               # MySQL密码
  database: "autodatahub"    # MySQL数据库名
  charset: "utf8mb4"         # 字符集

# 车辆类型配置
vehicle_type:
  default_queue: "default_triggers"
  # Vehicle type queues
  type_a_queue: "type_a_triggers"
  type_b_queue: "type_b_triggers"
  type_c_queue: "type_c_triggers"
  # Usage type queues
  production_car_queue: "production_car_triggers"
  test_drive_car_queue: "test_drive_car_triggers"
  media_car_queue: "media_car_triggers"
  internal_car_queue: "internal_car_triggers"
  # Mapping rules
  vehicle_type_map:
    "A_量产车": "type_a_production_triggers"
    "A_试驾车": "type_a_test_drive_triggers"
    "A_媒体车": "type_a_media_triggers"
    "A_内部车": "type_a_internal_triggers"
    "B_量产车": "type_b_production_triggers"
    "B_试驾车": "type_b_test_drive_triggers"
    "B_媒体车": "type_b_media_triggers"
    "B_内部车": "type_b_internal_triggers"
    "C_量产车": "type_c_production_triggers"
    "C_试驾车": "type_c_test_drive_triggers"
    "C_媒体车": "type_c_media_triggers"
    "C_内部车": "type_c_internal_triggers"