# AutoDataHub-monitor 配置文件

# Redis配置
redis:
  addr: "localhost:6379"      # Redis服务器地址
  password: ""               # Redis密码
  db: 0                      # Redis数据库编号
  queue_name: "negative_triggers"  # Redis队列名称

# 触发器配置
trigger:
  api_base_url: "http://localhost:8080"  # API基础URL
  api_endpoint: "/api/triggers"          # API端点
  redis_addr: "localhost:6379"           # Redis服务器地址
  redis_password: ""                     # Redis密码
  redis_db: 0                            # Redis数据库编号
  redis_queue: "negative_triggers"       # Redis队列名称
  api_timeout: 30                        # 超时时间（秒）

# 日志配置
logger:
  level: "info"              # 日志级别：debug, info, warn, error, fatal
  file_path: "logs/app.log"  # 日志文件路径
  max_size: 100              # 单个日志文件最大大小（MB）
  max_backups: 3             # 最大保留的旧日志文件数量
  max_age: 7                 # 日志文件保留的最大天数
  compress: true             # 是否压缩旧日志文件
  console: true              # 是否同时输出到控制台