# AutoDataHub-monitor 配置文件

# Redis配置
redis:
  addr: "localhost:6379"      # Redis服务器地址
  password: ""               # Redis密码
  db: 0                      # Redis数据库编号
  queue_name: "negative_triggers"  # Redis队列名称

# 触发器配置
trigger:
  api_base_url: "http://localhost:8080"  # API基础URL
  api_endpoint: "/api/triggers"          # API端点
  redis_addr: "localhost:6379"           # Redis服务器地址
  redis_password: ""                     # Redis密码
  redis_db: 0                            # Redis数据库编号
  redis_queue: "negative_triggers"       # Redis队列名称
  api_timeout: 30                        # 超时时间（秒）